const handitems = [
    {status: "Free", nome: "Chá", id: 1}, 
    {status: "Free", nome: "Suco", id: 2}, 
    {status: "Free", nome: "Cenoura", id: 3}, 
    {status: "Free", nome: "Sorvete de Baunilha", id: 4},  
    {status: "Free", nome: "Refri", id: 19}, 
    {status: "Free", nome: "Soda", id: 20}, 
    {status: "Free", nome: "Suco de Bolhas 1978", id: 24}, 
    {status: "Free", nome: "Poção do Amor", id: 25}, 
    {status: "Free", nome: "Calippo", id: 26}, 
    {status: "Free", nome: "Sake", id: 28}, 
    {status: "Free", nome: "Suco de Tomate", id: 29}, 
    {status: "Free", nome: "Líquido Radioativo", id: 30}, 
    {status: "Free", nome: "Drink", id: 31},   
    {status: "Free", nome: "Peixe", id: 34}, 
    {status: "Free", nome: "Champanhe Rosa", id: 35}, 
    {status: "Free", nome: "Pêra", id: 36}, 
    {status: "Free", nome: "Pêssego Suculento", id: 37}, 
    {status: "Free", nome: "Laranja", id: 38}, 
    {status: "Free", nome: "Abacaxi", id: 39}, 
    {status: "Free", nome: "Suco de Laranja", id: 40}, 
    {status: "Free", nome: "Refri de Laranja", id: 42}, 
    {status: "Free", nome: "Suco de Bolhas", id: 43}, 
    {status: "Free", nome: "Energético Astrobar", id: 44}, 
    {status: "Free", nome: "Gelatina Laranja", id: 45}, 
    {status: "Free", nome: "Gelatina Verde", id: 46}, 
    {status: "Free", nome: "Gelatina Vermelha", id: 47}, 
    {status: "Free", nome: "Pirulito", id: 48}, 
    {status: "Free", nome: "Cupnuddles", id: 49}, 
    {status: "Free", nome: "Garrafa de Espumante", id: 50}, 
    {status: "Free", nome: "Salgadinho", id: 51}, 
    {status: "Free", nome: "Cheetos", id: 52}, 
    {status: "Free", nome: "Café Expresso Pequeno", id: 53}, 
    {status: "Free", nome: "Café Expresso Grande", id: 54}, 
    {status: "Free", nome: "Pepsi", id: 55}, 
    {status: "Free", nome: "Refrigerante de Cereja", id: 57}, 
    {status: "Free", nome: "Sangue fresco", id: 58}, 
    {status: "Free", nome: "Saco", id: 59}, 
    {status: "Free", nome: "Castanhas", id: 60}, 
    {status: "Free", nome: "Xarope", id: 61}, 
    {status: "Free", nome: "Água Envenenada", id: 62}, 
    {status: "Free", nome: "Saco de Pipocas", id: 63}, 
    {status: "Free", nome: "Limonadda", id: 64}, 
    {status: "Free", nome: "Milkshake de Banana", id: 66}, 
    {status: "Free", nome: "Doce Azul", id: 67}, 
    {status: "Free", nome: "Doce Vermelho", id: 68}, 
    {status: "Free", nome: "Doce Verde", id: 69}, 
    {status: "Free", nome: "Coxa de Frango", id: 70}, 
    {status: "Free", nome: "Torrada", id: 71}, 
    {status: "Free", nome: "Perfume Azul", id: 72}, 
    {status: "Free", nome: "Eggnog", id: 73}, 
    {status: "Free", nome: "Cálice Medieval", id: 74}, 
    {status: "Free", nome: "Sorvete de Morango", id: 75}, 
    {status: "Free", nome: "Sorvete de Anis", id: 76}, 
    {status: "Free", nome: "Sorvete de Chocolate", id: 77}, 
    {status: "Free", nome: "Algodão Doce Rosa", id: 79}, 
    {status: "Free", nome: "Algodão Doce Azul", id: 80}, 
    {status: "Free", nome: "Cachorro Quente", id: 81}, 
    {status: "Free", nome: "Luneta", id: 82}, 
    {status: "Free", nome: "Maçã Delícia", id: 83}, 
    {status: "Free", nome: "Boneco de Biscoito", id: 84}, 
    {status: "Free", nome: "Americano", id: 85}, 
    {status: "Free", nome: "Frappuccino", id: 86}, 
    {status: "Free", nome: "Canecão D'Água", id: 87}, 
    {status: "Free", nome: "Rum", id: 88}, 
    {status: "Free", nome: "Cupcake", id: 89}, 
    {status: "Free", nome: "Pink Lemonade", id: 90}, 
    {status: "Free", nome: "Chá Oriental", id: 91}, 
    {status: "Free", nome: "Bombom Azul", id: 92}, 
    {status: "Free", nome: "Bombom Rosa", id: 93}, 
    {status: "Free", nome: "Chiclete Rosa", id: 94}, 
    {status: "Free", nome: "Chiclete Verde", id: 95}, 
    {status: "Free", nome: "Fatia de Bolo", id: 96}, 
    {status: "Free", nome: "Croissant", id: 97}, 
    {status: "Free", nome: "Tomate", id: 98}, 
    {status: "Free", nome: "Beringela", id: 99}, 
    {status: "Free", nome: "Repolho", id: 100}, 
    {status: "Free", nome: "Suco Borbulhante", id: 101}, 
    {status: "Free", nome: "Energético", id: 102}, 
    {status: "Free", nome: "Banana", id: 103}, 
    {status: "Free", nome: "Abacate", id: 104}, 
    {status: "Free", nome: "Uvas", id: 105}, 
    {status: "Free", nome: "Vitamina", id: 106}, 
    {status: "Free", nome: "Vitamina", id: 107}, 
    {status: "Free", nome: "Halter", id: 108}, 
    {status: "Free", nome: "Hambúrguer", id: 109}, 
    {status: "Free", nome: "Folha de Pápel", id: 110}, 
    {status: "Free", nome: "Carangueijo", id: 111}, 
    {status: "Free", nome: "Pimenta", id: 112},
    {status: "Free", nome: "Suco de Laranja", id: 113}, 
    {status: "Free", nome: "Suco de Limão", id: 114}, 
    {status: "Free", nome: "Suco de Groselha", id: 115}, 
    {status: "Free", nome: "Limão", id: 116}, 
    {status: "Free", nome: "Biscoito", id: 117}, 
    {status: "Free", nome: "Remune Rosa", id: 118}, 
    {status: "Free", nome: "Remune Azul", id: 119}, 
    {status: "Free", nome: "Frozen Azul", id: 120}, 
    {status: "Free", nome: "Frozen Rosa", id: 121}, 
    {status: "Free", nome: "Takoyaki", id: 122}, 
    {status: "Free", nome: "Salada", id: 123}, 
    {status: "Free", nome: "Milkshake Açaí", id: 124}, 
    {status: "Free", nome: "Milkshake Menta", id: 125}, 
    {status: "Free", nome: "Milkshake Tutti-Frutti", id: 126}, 
    {status: "Free", nome: "Casquinha Nutella", id: 127}, 
    {status: "Free", nome: "Casquinha de Açaí", id: 128}, 
    {status: "Free", nome: "Caixinha Rosa", id: 129}, 
    {status: "Free", nome: "Queijo", id: 130}, 
    {status: "Free", nome: "Baguete", id: 131}, 
    {status: "Free", nome: "Camarão", id: 132}, 
    {status: "Free", nome: "Brócolis", id: 133}, 
    {status: "Free", nome: "Melância", id: 134}, 
    {status: "Free", nome: "Donuts", id: 135}, 
    {status: "Free", nome: "Minhoca", id: 136}, 
    {status: "Free", nome: "Picolé", id: 137}, 
    {status: "Free", nome: "Doritos Azul", id: 138}, 
    {status: "Free", nome: "Rosa Vermelha", id: 1000}, 
    {status: "Free", nome: "Rosa Negra", id: 1001}, 
    {status: "Free", nome: "Girassol", id: 1002}, 
    {status: "Free", nome: "Livro Vermelho", id: 1003}, 
    {status: "Free", nome: "Livro Azul", id: 1004}, 
    {status: "Free", nome: "Livro Verde", id: 1005}, 
    {status: "Free", nome: "Flor de Leite", id: 1006}, 
    {status: "Free", nome: "Erva dos Feitiços", id: 1007}, 
    {status: "Free", nome: "Delícia Amarela", id: 1008}, 
    {status: "Free", nome: "Pandemia Rosa", id: 1009}, 
    {status: "Free", nome: "Prancheta", id: 1011}, 
    {status: "Free", nome: "Seringa", id: 1014}, 
    {status: "Free", nome: "Bolsa Hospitalar", id: 1015}, 
    {status: "Free", nome: "Flor Bolly", id: 1019},  
    {status: "Free", nome: "Hyacinthus Vermelho", id: 1021}, 
    {status: "Free", nome: "Hyacinthus Azul", id: 1022}, 
    {status: "Free", nome: "Amarílis", id: 1023}, 
    {status: "Free", nome: "Pudim de Chocolate", id: 1024}, 
    {status: "Free", nome: "Doce Natalino", id: 1025}, 
    {status: "Free", nome: "Presente", id: 1026}, 
    {status: "Free", nome: "Vela", id: 1027}, 
    {status: "Free", nome: "Cereal", id: 1028}, 
    {status: "Free", nome: "Balão Bege", id: 1029}, 
    {status: "Free", nome: "Tablet", id: 1030}, 
    {status: "Free", nome: "Tocha Olímpica", id: 1031}, 
    {status: "Free", nome: "Major Tom", id: 1032}, 
    {status: "Free", nome: "OVNI", id: 1033}, 
    {status: "Free", nome: "Alien", id: 1034}, 
    {status: "Free", nome: "Chave de Boca", id: 1035}, 
    {status: "Free", nome: "Pato Verde", id: 1036}, 
    {status: "Free", nome: "Cobra", id: 1037}, 
    {status: "Free", nome: "Pau", id: 1038}, 
    {status: "Free", nome: "Mão machucada", id: 1039}, 
    {status: "Free", nome: "Coração", id: 1040}, 
    {status: "Free", nome: "Lula", id: 1041}, 
    {status: "Free", nome: "Cocô", id: 1042}, 
    {status: "Free", nome: "Verme", id: 1043}, 
    {status: "Free", nome: "Rato Morto", id: 1044}, 
    {status: "Free", nome: "Dentadura", id: 1045}, 
    {status: "Free", nome: "Caixa de Leite", id: 1046}, 
    {status: "Free", nome: "Bola de Canhão", id: 1047}, 
    {status: "Free", nome: "Bandeira Preta", id: 1048}, 
    {status: "Free", nome: "Marreta", id: 1049}, 
    {status: "Free", nome: "Ovo Rosa", id: 1050}, 
    {status: "Free", nome: "Pincel", id: 1051}, 
    {status: "Free", nome: "Bandeira Branca", id: 1052}, 
    {status: "Free", nome: "Pato Amarelo", id: 1053}, 
    {status: "Free", nome: "Balão Laranja", id: 1054}, 
    {status: "Free", nome: "Balão Verde", id: 1055}, 
    {status: "Free", nome: "Balão Azul", id: 1056}, 
    {status: "Free", nome: "Balão Rosa", id: 1057}, 
    {status: "Free", nome: "Lamparina", id: 1058}, 
    {status: "Free", nome: "Papen Higiénico", id: 1059}, 
    {status: "Free", nome: "Spray", id: 1060}, 
    {status: "Free", nome: "Margarida", id: 1061}, 
    {status: "Free", nome: "Caveiras de Doces Rosa", id: 1062}, 
    {status: "Free", nome: "Caveiras de Doces Verde", id: 1063}, 
    {status: "Free", nome: "Caveiras de Doces Azul", id: 1064}, 
    {status: "Free", nome: "Boneca Emília", id: 1065}, 
    {status: "Free", nome: "Ursinho", id: 1066}, 
    {status: "Free", nome: "Soldadinho", id: 1067}, 
    {status: "Free", nome: "Mangá", id: 1068}, 
    {status: "Free", nome: "Quadrinho", id: 1069}, 
    {status: "Free", nome: "Livro Amarelo", id: 1070}, 
    {status: "Free", nome: "Tablet Dourado", id: 1071}, 
    {status: "Free", nome: "Celular", id: 1072}, 
    {status: "Free", nome: "Ovo de Dinossauro", id: 1073}, 
    {status: "Free", nome: "Ovo de Alossauro ", id: 1074}, 
    {status: "Free", nome: "Ovo de Tríceratops", id: 1075}, 
    {status: "Free", nome: "Ovo de Saurolofo", id: 1076}, 
    {status: "Free", nome: "Toalhinha", id: 1077}, 
    {status: "Free", nome: "Espeto de Lagarto", id: 1078}, 
    {status: "Free", nome: "Besouro Lucano", id: 1079}, 
    {status: "Free", nome: "Besouro Rinoceronte", id: 1080}, 
    {status: "Free", nome: "Regador Verde", id: 1081}, 
    {status: "Free", nome: "Bandeira LGBT", id: 1082}, 
    {status: "Free", nome: "Abóbora Halloween", id: 1083}, 
    {status: "Free", nome: "Bolsa de Compras", id: 1084}, 
    {status: "Free", nome: "Filme de Ação", id: 1085}, 
    {status: "Free", nome: "Filme de Patinho", id: 1086}, 
    {status: "Free", nome: "Diário", id: 1087}, 
    {status: "Free", nome: "Lápis", id: 1088}, 
    {status: "Free", nome: "Vara com Peixe", id: 1090}, 
    {status: "Free", nome: "Vara com Bota", id: 1091}, 
    {status: "Free", nome: "Vara com Garrafa", id: 1092}, 
    {status: "Free", nome: "Bandeira Amarela", id: 1093}, 
    {status: "Free", nome: "Espada", id: 1094}, 
    {status: "Free", nome: "Coração", id: 1095},
    {status: "Free", nome: "Celular", id: 1096},
    {status: "Free", nome: "Plantinha", id: 1097},
    {status: "Free", nome: "Robozinho", id: 1098},
    {status: "Free", nome: "Ursinho Teddy", id: 1099},
    {status: "Free", nome: "Pato Férias", id: 1100},
    {status: "Free", nome: "Bola de Futebol", id: 1101},
    {status: "Free", nome: "Taco do Diálogo", id: 1102},
    {status: "Free", nome: "Bola de Tênis", id: 1103},
    {status: "Free", nome: "Torrada Hello Kitty", id: 1104},
    {status: "Free", nome: "H-Phone", id: 1105},
    {status: "Free", nome: "Microfone DR Sports", id: 1106},
    {status: "Free", nome: "Poção Kryptomon", id: 1107},
    {status: "Free", nome: "Refrigerante de Urso", id: 1108},
    {status: "Free", nome: "Suquinho de Laranja", id: 1109},
    {status: "Free", nome: "Suquinho de Morango", id: 1111},
    {status: "Free", nome: "Suquinho de Pera", id: 1112},
    {status: "Free", nome: "Casquinha de Baunilha", id: 1113},
    {status: "Free", nome: "Casquinha de Chocolate", id: 1114},
    {status: "Free", nome: "Casquinha de Morango", id: 1115},
    {status: "Free", nome: "Sorvete Colorido", id: 1116},
]